/* =========================================================
BOREHOLE DATA
Every dataType object uses the same keys as FILTER_CONFIG.
Any category not present is treated as false by the
filtering function.
========================================================= */

const boreholes = [

    {
        id: "327-U1362A",
        coords: [47.7610466667, -127.7612],
        description: "Injection site.",

        dataType: {
            coringSummary: true,
            coreSectionSummary: false,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: true,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: true,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: true,
            xRay: true,
            gammaRay: true,
            heatFlow: true,
            boreholePressure: true,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: true,
            reflectanceSpectroscopy: true,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: true,
            pieceLog: true,
            corelog: true,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: true
        }
    },


    {
        id: "327-U1362B",
        coords: [47.7583283333, -127.7621866667],
        description: "Monitoring site.",

        dataType: {
            coringSummary: true,
            coreSectionSummary: false,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: false,
            corePhotoImages: true,
            coreSections: true,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: true,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: true,
            corelog: true,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "168-1026A",
        coords: [47.7626, -127.759],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: true,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: true,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: true,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: true,
            smearSlides: true,
            sulfurIsotopic: true,
            traceElement: true,
            bottomWaterOxygen: true,
            seafloorPressure: true,
            oceanCurrents: true,
            boreholeTemp: true,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: true,
            depthAgeModel: true,
            permeability: false
        }
    },


    {
        id: "168-1026B",
        coords: [47.7627, -127.759],
        description: "Connected to ONC cable network.",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: true,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: true,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: true,
            bottomWaterOxygen: true,
            seafloorPressure: true,
            oceanCurrents: true,
            boreholeTemp: true,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: true,
            depthAgeModel: false,
            permeability: true
        }
    },


    {
        id: "168-1026C",
        coords: [47.771, -127.753],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: true,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: true,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: false,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: true,
            smearSlides: false,
            sulfurIsotopic: true,
            traceElement: true,
            bottomWaterOxygen: true,
            seafloorPressure: true,
            oceanCurrents: true,
            boreholeTemp: true,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: false,
            depthAgeModel: true,
            permeability: false
        }
    },


    {
        id: "168-1027A",
        coords: [47.7569, -127.73],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: false,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: false,
            corePhotoImages: false,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: false,
            gammaRay: true,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: false,
            pWaveVelocity: true,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "168-1027B",
        coords: [47.7569, -127.73],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: true,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: true,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: true,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: true,
            depthAgeModel: true,
            permeability: false
        }
    },


    {
        id: "168-1027C",
        coords: [47.7565, -127.730],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: true,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: false,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "301-U1301A",
        coords: [47.7534916667, -127.7638816667],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: false,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: false,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: false,
            corePhotoImages: false,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: false,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: true,
            bulkDensity: false,
            moistureDensity: false,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: false,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: true
        }
    },


    {
        id: "301-U1301B",
        coords: [47.75381, -127.76377],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: true,
            bulkDensity: false,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: false,
            thermalConductivity: true,
            resistivity: true,
            icpAesSolids: true,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: true
        }
    },


    {
        id: "301-U1301C",
        coords: [47.754665, -127.76333333333],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: true,
            gammaRay: true,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: true,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: true,
            seafloorPressure: true,
            oceanCurrents: true,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "301-U1301D",
        coords: [47.7546, -127.763005],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: false,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: false,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: false,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "328-U1364A",
        coords: [48.6999366667, -126.8722151667],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: false,
            siteMap: true,
            bathymetry: false,
            visualCoreDesc: false,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: false,
            corePhotoImages: false,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: false,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: false,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: true,
            oceanCurrents: true,
            boreholeTemp: true,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: false,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: true
        }
    },


    {
        id: "146-889A",
        coords: [48.6993, -126.8683],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: true,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: true,
            pWaveVelocity: false,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: true,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "146-889B",
        coords: [48.6975, -126.8732],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: false,
            thermalConductivity: true,
            resistivity: true,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "146-889C",
        coords: [48.6985, -126.8705],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: false,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: false,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: false,
            corePhotoImages: false,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: false,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: false,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: false,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "146-889D",
        coords: [48.6999, -126.8688],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: true,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: false,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: true,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "311-U1327A",
        coords: [48.6981166667, -126.86535],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: false,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: false,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: false,
            corePhotoImages: false,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: false,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: false,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: true,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: false,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "311-U1327B",
        coords: [48.69815, -126.8652333333],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: false,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: false,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: true,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "311-U1327C",
        coords: [48.69815, -126.8652333333],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: true,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "311-U1327D",
        coords: [48.69825, -126.8651],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: true,
            icpAesSolids: false,
            reflectanceSpectroscopy: true,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "311-U1327E",
        coords: [48.698333, -126.864933],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: true,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: true,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "146-891B",
        coords: [44.644300, -125.326],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: false,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: false,
            depthAgeModel: false,
            permeability: true
        }
    },


    {
        id: "146-892D",
        coords: [44.674, -125.119],
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: false,
            visualCoreDesc: true,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: true,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: false,
            depthAgeModel: false,
            permeability: true
        }
    }

];
