/* =========================================================
BOREHOLE DATA
Every dataType object uses the same keys as FILTER_CONFIG.
Any category not present is treated as false by the
filtering function.
========================================================= */

const boreholes = [

    {
        id: "327-U1362A",
        leg: 327,
        coords: [47.7610467, -127.7612],
        reportedLocation: [47.7610467, -127.7612],
        waterDepth: 2661.13,
        penetration: 528,
        description: "Injection site.",

        dataType: {
            coringSummary: true,
            coreSectionSummary: false,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: true,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: true,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: true,
            xRay: true,
            gammaRay: true,
            heatFlow: true,
            boreholePressure: true,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: true,
            reflectanceSpectroscopy: true,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: true,
            pieceLog: true,
            corelog: true,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: true
        }
    },


    {
        id: "327-U1362B",
        leg: 327,
        coords: [47.7583283, -127.7621867],
        reportedLocation: [47.7583283, -127.7621867],
        waterDepth: 2661.13,
        penetration: 359,
        description: "Monitoring site.",

        dataType: {
            coringSummary: true,
            coreSectionSummary: false,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: false,
            corePhotoImages: true,
            coreSections: true,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: true,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: true,
            corelog: true,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "168-1026A",
        leg: 168,
        coords: [47.762695, -127.758911],
        reportedLocation: [47.7626, -127.759],
        waterDepth: 2658.1,
        penetration: 101.4,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: true,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: true,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: true,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: true,
            smearSlides: true,
            sulfurIsotopic: true,
            traceElement: true,
            bottomWaterOxygen: true,
            seafloorPressure: true,
            oceanCurrents: true,
            boreholeTemp: true,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: true,
            depthAgeModel: true,
            permeability: false
        }
    },


    {
        id: "168-1026B",
        leg: 168,
        coords: [47.7626, -127.7592116667],
        reportedLocation: [47.7627, -127.759],
        waterDepth: 2657.9,
        penetration: 39.2,
        description: "Connected to ONC cable network.",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: true,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: true,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: true,
            bottomWaterOxygen: true,
            seafloorPressure: true,
            oceanCurrents: true,
            boreholeTemp: true,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: true,
            depthAgeModel: false,
            permeability: true
        }
    },


    {
        id: "168-1026C",
        leg: 168,
        coords: [47.771, -127.753],
        reportedLocation: [47.771, -127.753],
        waterDepth: 2657.8,
        penetration: 163.6,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: true,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: true,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: false,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: true,
            smearSlides: false,
            sulfurIsotopic: true,
            traceElement: true,
            bottomWaterOxygen: true,
            seafloorPressure: true,
            oceanCurrents: true,
            boreholeTemp: true,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: false,
            depthAgeModel: true,
            permeability: false
        }
    },


    {
        id: "168-1027A",
        leg: 168,
        coords: [47.7569, -127.73],
        reportedLocation: [47.7569, -127.73],
        waterDepth: 2657.0,
        penetration: 9.5,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: false,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: false,
            corePhotoImages: false,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: false,
            gammaRay: true,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: false,
            pWaveVelocity: true,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "168-1027B",
        leg: 168,
        coords: [47.7569, -127.73],
        reportedLocation: [47.7569, -127.73],
        waterDepth: 2657.0,
        penetration: 577.9,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: true,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: true,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: true,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: true,
            depthAgeModel: true,
            permeability: false
        }
    },


    {
        id: "168-1027C",
        leg: 168,
        coords: [47.7565, -127.731],
        reportedLocation: [47.7565, -127.73],
        waterDepth: 2656.2,
        penetration: 632.4,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: true,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: false,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "301-U1301A",
        leg: 301,
        coords: [47.7534917, -127.7638817],
        reportedLocation: [47.7534917, -127.7638817],
        waterDepth: 2656.64,
        penetration: 369.5,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: false,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: false,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: false,
            corePhotoImages: false,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: false,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: true,
            bulkDensity: false,
            moistureDensity: false,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: false,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: true
        }
    },


    {
        id: "301-U1301B",
        leg: 301,
        coords: [47.75381, -127.76377],
        reportedLocation: [47.75381, -127.76377],
        waterDepth: 2656.75,
        penetration: 582.8,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: true,
            bulkDensity: false,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: false,
            thermalConductivity: true,
            resistivity: true,
            icpAesSolids: true,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: true
        }
    },


    {
        id: "301-U1301C",
        leg: 301,
        coords: [47.754665, -127.7633333],
        reportedLocation: [47.754665, -127.7633333],
        waterDepth: 2655.95,
        penetration: 265.3,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: true,
            gammaRay: true,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: true,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: true,
            seafloorPressure: true,
            oceanCurrents: true,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "301-U1301D",
        leg: 301,
        coords: [47.7546, -127.763005],
        reportedLocation: [47.7546, -127.763005],
        waterDepth: 2655.35,
        penetration: 177,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: false,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: false,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: false,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "328-U1364A",
        leg: 328,
        coords: [48.6999367, -126.8721517],
        reportedLocation: [48.6999367, -126.8721517],
        waterDepth: 1317.66,
        penetration: 336,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: false,
            siteMap: true,
            bathymetry: false,
            visualCoreDesc: false,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: false,
            corePhotoImages: false,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: false,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: false,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: true,
            oceanCurrents: true,
            boreholeTemp: true,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: false,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: true
        }
    },


    {
        id: "146-889A",
        leg: 146,
        coords: [48.6993, -126.8683],
        reportedLocation: [48.6993, -126.8683],
        waterDepth: 1311.2,
        penetration: 345.8,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: true,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: true,
            pWaveVelocity: false,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: true,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "146-889B",
        leg: 146,
        coords: [48.6975, -126.8732],
        reportedLocation: [48.6975, -126.8732],
        waterDepth: 1316.2,
        penetration: 386.5,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: false,
            thermalConductivity: true,
            resistivity: true,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "146-889C",
        leg: 146,
        coords: [48.6985, -126.8705],
        reportedLocation: [48.6985, -126.8705],
        waterDepth: 1315.1,
        penetration: 384.5,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: false,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: false,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: false,
            corePhotoImages: false,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: false,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: false,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: false,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "146-889D",
        leg: 146,
        coords: [48.6997, -126.8688],
        reportedLocation: [48.6997, -126.8688],
        waterDepth: 1311.1,
        penetration: 154,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: true,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: false,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: true,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "311-U1327A",
        leg: 311,
        coords: [48.6981167, -126.86535],
        reportedLocation: [48.6981167, -126.86535],
        waterDepth: 1322.1,
        penetration: 300,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: false,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: false,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: false,
            corePhotoImages: false,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: false,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: false,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: true,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: false,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: false,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "311-U1327B",
        leg: 311,
        coords: [48.69815, -126.8652333],
        reportedLocation: [48.69815, -126.8652333],
        waterDepth: 1306.1,
        penetration: 9.5,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: false,
            chemWaterSamples: false,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: false,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: false,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: true,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "311-U1327C",
        leg: 311,
        coords: [48.69815, -126.8652333],
        reportedLocation: [48.69815, -126.8652333],
        waterDepth: 1304.5,
        penetration: 300,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: true,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "311-U1327D",
        leg: 311,
        coords: [48.69825, -126.8651],
        reportedLocation: [48.69825, -126.8651],
        waterDepth: 1303.7,
        penetration: 300,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: true,
            icpAesSolids: false,
            reflectanceSpectroscopy: true,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "311-U1327E",
        leg: 311,
        coords: [48.6983333, -126.8649333],
        reportedLocation: [48.6983333, -126.8649333],
        waterDepth: 1303.4,
        penetration: 300,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: true,
            visualCoreDesc: true,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: false,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: true,
            pWaveVelocity: false,
            shearStrength: false,
            thermalConductivity: false,
            resistivity: true,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: false,
            paleoInvestigation: false,
            rangeTable: false,
            ageProfile: false,
            depthAgeModel: false,
            permeability: false
        }
    },


    {
        id: "146-891B",
        leg: 146,
        coords: [44.6443, -125.326],
        reportedLocation: [44.6443, -125.326],
        waterDepth: 2663.0,
        penetration: 472.3,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: false,
            visualCoreDesc: true,
            lithology: true,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: true,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: false,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: false,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: false,
            depthAgeModel: false,
            permeability: true
        }
    },


    {
        id: "146-892D",
        leg: 146,
        coords: [44.674, -125.119],
        reportedLocation: [44.674, -125.119],
        waterDepth: 670.3,
        penetration: 166.5,
        description: "",

        dataType: {
            coringSummary: true,
            coreSectionSummary: true,
            siteMap: true,
            bathymetry: false,
            visualCoreDesc: true,
            lithology: false,
            seismicProfile: true,
            thinSections: false,
            coreCloseups: true,
            corePhotoImages: true,
            coreSections: false,
            chemRockEval: false,
            chemCarbonates: false,
            chemGasElem: true,
            chemWaterSamples: true,
            downHoleTemp: true,
            magSusceptibility: true,
            magRemanence: false,
            xRay: true,
            gammaRay: false,
            heatFlow: false,
            boreholePressure: false,
            bulkDensity: true,
            moistureDensity: true,
            pWaveVelocity: true,
            shearStrength: true,
            thermalConductivity: true,
            resistivity: false,
            icpAesSolids: false,
            reflectanceSpectroscopy: false,
            smearSlides: true,
            sulfurIsotopic: false,
            traceElement: false,
            bottomWaterOxygen: false,
            seafloorPressure: false,
            oceanCurrents: false,
            boreholeTemp: false,
            earthquakeCatalogue: true,
            photomicrographs: false,
            pieceLog: false,
            corelog: true,
            cryomag: true,
            paleoInvestigation: true,
            rangeTable: true,
            ageProfile: false,
            depthAgeModel: false,
            permeability: true
        }
    }

];
